---
abstract: 'Perl extension for IETF IDN WG ACE character conversions'
author:
  - 'James Briggs <james.briggs@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IETF-ACE
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: 0
  Unicode::String: 0
version: 0.04
